import React, { createContext, useContext, useMemo, useState } from 'react';

type Language = 'en' | 'hi' | 'mr';

type TranslationDictionary = Record<string, string>;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const translations: Record<Language, TranslationDictionary> = {
  en: {
    'header.nav.home': 'Home',
    'header.nav.services': 'Services',
    'header.nav.whyUs': 'Why Us',
    'header.nav.ourTeam': 'Our Team',
    'header.nav.gallery': 'Gallery',
    'header.nav.successStories': 'Success Stories',
    'header.nav.blog': 'Blog',
    'header.nav.contactUs': 'Contact Us',
    'header.address.line1': '2nd floor, Kumar Prism, Road, above Yes Bank',
    'header.address.line2': 'opp. Fab India, Kirtane Baug, Amanora Park Town, Hadapsar, Pune',
    'header.bookAppointment': 'Book an Appointment',
    'header.hospitalName': 'Babygen IVF Centre',
    'header.location': 'Pune',
    'header.location2': 'Gurugram',
    'header.serviceDetails': 'Service Details',
    'header.viewAll': 'View All',
    'doctor.name': 'Dr. Bhavna Sharma',
    'doctor.position': 'MBBS, DGO | IVF & Infertility Specialist',
    'doctor.heading.prefix': 'A Message from',
    'doctor.heading.name': 'Dr. Bhavna Sharma',
    'doctor.subtitle': 'IVF Specialist, Babygen IVF Centre, Pune',
    'doctor.p1.start': 'At the heart of Babygen IVF lies a passionate vision brought to life by Dr. Bhavna Sharma, a dexterous and dedicated IVF specialist with',
    'doctor.p1.h1': 'more than 20 years of experience',
    'doctor.p1.mid1': '. Her journey began at the prestigious',
    'doctor.p1.h2': 'Maulana Azad Medical College (MAMC), Delhi University',
    'doctor.p1.mid2': ', where she completed her',
    'doctor.p1.h3': 'MBBS and DGO',
    'doctor.p2.start': 'Her pursuit of excellence took her to Europe for advanced learning, including refined training at',
    'doctor.p2.h1': 'Landes-Frauen-Und Kinderklinik, Linz',
    'doctor.p2.mid1': ', a',
    'doctor.p2.h2': 'Masters course in Assisted Reproductive Technology (ART)',
    'doctor.p2.mid2': ', and a',
    'doctor.p2.h3': 'Diploma in Pelvic Endoscopy from Kiel University, Germany',
    'doctor.p3.start': 'With rich international exposure, Dr. Sharma pioneered',
    'doctor.p3.h1': 'Kalyan IVF Centre in Gwalior',
    'doctor.p3.mid1': ', bringing hope to couples dreaming of parenthood. She has performed',
    'doctor.p3.h2': 'over 10,000 IVF and ICSI procedures',
    'doctor.p3.mid2': ', resulting in',
    'doctor.p3.h3': 'more than 8,000 successful IVF pregnancies',
    'doctor.p3.end': ', blending science with compassionate care.',
    'doctor.p4.start': 'Babygen IVF opens a new chapter as Dr. Sharma extends her expertise to',
    'doctor.p4.h1': 'Pune and Gurugram',
    'doctor.p4.mid1': ', with centres equipped with cutting-edge embryology labs, advanced diagnostics, and the latest innovations in',
    'doctor.p4.h2': 'IVF, ICSI, egg freezing, and fertility preservation',
    'doctor.p4.end': 'ensuring personalized care and excellent outcomes for aspiring parents.',
    'doctor.cta': 'Book an Appointment',
    'hero.title': 'Dreaming of Parenthood?',
    'hero.subtitle': 'Your Journey Begins Here With Advanced IVF Care',
    'hero.badge': 'Special Offer',
    'hero.bookAppointment': 'Book Appointment',
    'hero.selectService': 'Select Service',
    'hero.service.ivf': 'IVF Treatment',
    'hero.service.consultation': 'Consultation',
    'hero.service.gynaecologist': 'Gynaecologist',
    'hero.input.name': 'Your Name',
    'hero.input.email': 'Email Address (Optional)',
    'hero.input.phone': 'Phone Number',
    'hero.requestCallback': 'Request Callback',
    'hero.status.sending': 'Sending your request...',
    'hero.status.success': 'Request sent successfully! We will contact you shortly.',
    'hero.status.failed': 'Failed to send request. Please try again.',
    'header.nav.doctors': 'Doctors',
    'header.nav.centers': 'Fertility Centers',
    'header.nav.stories': 'Web Stories',
    'common.bookAppointment': 'Book Appointment',
    'common.submit': 'Submit',
    'common.offerLine': 'Save upto Rs. 40000. Only 3 slots left!!',
    'common.saveUpto': 'Save upto Rs. 40000',
    'common.slotsLeft': 'Only 3 slots left!!',
    'common.callUs': 'Call Us',
    'common.bookConsultation': 'Book Consultation',
    'common.chatWhatsapp': 'Chat on WhatsApp',
    'common.callNow': 'Call Now',
    'hero.mainHeadingTop': 'Your Journey to',
    'hero.mainHeadingBottom': 'Parenthood Starts Here',
    'hero.description': 'Advanced fertility care designed to support every step of your parenthood journey from medication-based treatments to advanced procedures like IVF and ICSI, guided by experienced specialists who care.',
    'hero.form.heading': 'Get Personalized Consultation!',
    'hero.form.tcPrefix': 'By continuing, you agree to our',
    'hero.form.tc': 'T&C',
    'hero.form.and': 'and',
    'hero.form.privacy': 'Privacy Policies',
    'hero.form.whatsappOptin': 'Opt-in for WhatsApp updates',
    'hero.stats.babies': 'IVF Babies Born',
    'hero.stats.cities': 'Cities in India',
    'hero.stats.experience': 'Years Of Experienced Doctors',
    'hero.stats.bornTillDate': 'IVF Babies Born till date',
    'hero.stats.everyMonth': 'IVF Babies every month',
    'hero.stats.ivfExperience': 'Years Of Experience in IVF and Infertility Treatment',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Request a consultation today',
    'contact.input.name': 'Your Name',
    'contact.input.email': 'Your Email Address (Optional)',
    'contact.input.phone': 'Your Phone Number',
    'contact.submit': 'Send Request',
    'contact.info.phone': 'Phone',
    'contact.info.email': 'Email',
    'contact.info.address': 'Address',
    'contact.info.hours': 'Hours',
    'contact.info.addressValue': '2nd Floor, Kumar Prism, Amanora Park Town, Hadapsar, Pune',
    'contact.info.hoursValue': 'Mon – Sat: 9:00 AM – 7:00 PM',
    'doctor.expertMessage': 'IVF Expert Message',
    'doctor.stat.years': 'Years',
    'doctor.stat.ivficsi': 'IVF/ICSI',
    'doctor.stat.successes': 'Successes',
    'doctor.badge.years': '20+ Years',
    'doctor.badge.ivficsi': 'IVF + ICSI',
    'doctor.badge.global': 'Global Training',
    'marquee.title': 'IVF Success By Our Team Covered Across Media',
    'gated.badge': 'Free IVF Decision Resources',
    'gated.title': 'Before You Choose an IVF Centre, Read This First',
    'gated.description': 'In 20+ years, our team has supported 8000+ couples across 14 countries. These resources help you avoid costly mistakes and make confident treatment decisions.',
    'gated.stats.couples': 'Couples Supported',
    'gated.stats.countries': 'Countries',
    'gated.stats.years': 'Years Experience',
    'gated.riskTitle': 'What goes wrong with poor IVF centre selection?',
    'gated.verifyTitle': 'What should you verify before starting IVF?',
    'gated.risk1': 'Inexperienced doctors and embryologists can significantly reduce success rates.',
    'gated.risk2': 'Poorly equipped labs can impact embryo quality and treatment outcomes.',
    'gated.risk3': 'Low-quality consumables may reduce overall effectiveness of treatment.',
    'gated.risk4': 'Hidden costs are often added later for injections, tests, and procedures.',
    'gated.verify1': 'Ask for age-wise and case-wise success data, not only marketing claims.',
    'gated.verify2': 'Confirm all major costs in writing before starting treatment.',
    'gated.verify3': 'Check if the center has complete IVF + ICSI + freezing infrastructure.',
    'gated.verify4': 'Verify whether the same specialist will manage your full cycle.',
    'gated.resourceLabel': 'Resource',
    'gated.resource1.title': '5 Mistakes That Reduce IVF Success Chances',
    'gated.resource1.desc': 'Avoid common decisions that waste time, increase stress, and lower outcomes.',
    'gated.resource1.cta': 'Unlock This Guide',
    'gated.resource2.title': '7 Problems People Face While Choosing IVF in Pune',
    'gated.resource2.desc': 'Spot red flags early and choose a center that is transparent and clinically strong.',
    'gated.resource2.cta': 'Read Before You Decide',
    'gated.resource3.title': 'Questions You Must Ask Before Starting IVF',
    'gated.resource3.desc': 'Use this checklist in your first consultation so you can compare centers fairly.',
    'gated.resource3.cta': 'Get The Question List',
    'gated.helpTitle': 'Need help deciding quickly?',
    'gated.helpDesc': 'Talk to our IVF counsellor and get a personalized treatment roadmap.',
    'gated.bookFree': 'Book Free Consultation',
    'videos.badge': 'Real Patient Journeys',
    'videos.title': 'IVF Success Stories',
    'videos.subtitle': 'Watch real families share their treatment journey, outcomes, and experience with our fertility team.',
    'videos.scrollLeft': 'Scroll left',
    'videos.scrollRight': 'Scroll right',
    'videos.realStory': 'Real Story',
    'videos.likeStory': 'Like story',
    'videos.shareStory': 'Share story',
    'videos.swipeHint': 'Swipe to explore more stories',
    'videos.title1': 'After 8 Years of Hope',
    'videos.title2': 'Our First Positive Result',
    'videos.title3': 'Trusted Team, Better Journey',
    'videos.title4': 'From Doubt to Parenthood',
    'videos.title5': 'High-Risk Case, Happy Ending',
    'videos.treatment1': 'IVF + ICSI',
    'videos.treatment2': 'IVF',
    'videos.treatment3': 'Consultation + IVF',
    'videos.treatment4': 'IVF + Embryo Transfer',
    'videos.treatment5': 'Advanced Fertility Care',
    'videos.views1': '15.4K Views',
    'videos.views2': '7.4K Views',
    'videos.views3': '5.3K Views',
    'videos.views4': '27.5K Views',
    'videos.views5': '13.6K Views',
    'cert.badge': 'Certified Excellence',
    'cert.title': 'Certifications & Affiliations',
    'cert.subtitle': 'Our center adheres to the highest international standards of medical safety and ethical practices.',
    'cert.card1': 'Medical Accreditation',
    'cert.card2': 'IVF Specialization',
    'cert.card3': 'Clinical Excellence',
    'cert.card4': 'International Standards',
    'cert.card5': 'Laboratory Certification',
    'cert.card6': 'Quality Assurance',
    'cert.card7': 'Healthcare Compliance',
    'cert.card8': 'Safety Protocol',
    'cert.card9': 'Advanced Embryology',
    'cert.card10': 'Professional Affiliation',
    'cert.card11': 'Patient Care Award',
    'cert.card12': 'Innovation in IVF',
    'cert.badge1': 'ICMR ENROLLED',
    'cert.badge2': 'ISO CERTIFIED',
    'cert.badge3': 'ISAR AFFILIATED',
    'footer.about': 'Our team at Babygen IVF has helped thousands of childless couples achieve their dream of having a healthy baby. Our doctors and counsellors guide couples every step of the way.',
    'footer.contactTitle': 'Contact Us',
    'footer.linksTitle': 'Important Links',
    'footer.link.about': 'About Us',
    'footer.link.privacy': 'Privacy Policy',
    'footer.link.disclaimer': 'Disclaimer',
    'footer.link.contact': 'Contact Us',
    'footer.address': '2nd Floor, Kumar Prism, Amanora Park Town, Hadapsar, Pune',
    'footer.copyright': '© 2026 Babygen IVF, Pune. All rights reserved.',
    'thankyou.badge': 'Submission Confirmed',
    'thankyou.title': 'Thank You for Reaching Out',
    'thankyou.subtitle': 'Your request has been received successfully. Our fertility care team will connect with you shortly to guide you on the next best steps.',
    'thankyou.call': 'Call: 731 485 5000',
    'thankyou.whatsapp': 'Continue on WhatsApp',
    'thankyou.card1.title': 'What happens next?',
    'thankyou.card1.desc': 'Our coordinator calls you to understand your case and schedule your consultation.',
    'thankyou.card2.title': 'Keep your slot reserved',
    'thankyou.card2.desc': 'Share your preferred call time on WhatsApp to avoid delays in booking.',
    'thankyou.card3.title': 'Offer reminder',
    'thankyou.card3.desc': 'You can save up to Rs. 40000 on eligible treatment plans.',
    'thankyou.backHome': 'Back to Home',
    'notfound.message': 'Oops! Page not found',
    'notfound.backHome': 'Return to Home',
    'lang.english': 'English',
    'lang.hindi': 'Hindi',
    'lang.marathi': 'Marathi',
  },
  hi: {
    'header.nav.home': 'होम',
    'header.nav.services': 'सेवाएं',
    'header.nav.whyUs': 'हमें क्यों चुनें',
    'header.nav.ourTeam': 'हमारी टीम',
    'header.nav.gallery': 'गैलरी',
    'header.nav.successStories': 'सफलता की कहानियां',
    'header.nav.blog': 'ब्लॉग',
    'header.nav.contactUs': 'संपर्क करें',
    'header.address.line1': '2nd floor, Kumar Prism, Road, above Yes Bank',
    'header.address.line2': 'opp. Fab India, Kirtane Baug, Amanora Park Town, Hadapsar, Pune',
    'header.bookAppointment': 'अपॉइंटमेंट बुक करें',
    'header.hospitalName': 'बेबीजेन आईवीएफ सेंटर',
    'header.location': 'पुणे',
    'header.location2': 'गुरुग्राम',
    'header.serviceDetails': 'सेवा विवरण',
    'header.viewAll': 'सभी देखें',
    'doctor.name': 'डॉ. भावना शर्मा',
    'doctor.position': 'एमबीबीएस, डीजीओ | आईवीएफ एवं बांझपन विशेषज्ञ',
    'doctor.heading.prefix': 'संदेश',
    'doctor.heading.name': 'डॉ. भावना शर्मा का',
    'doctor.subtitle': 'आईवीएफ विशेषज्ञ, बेबीजेन आईवीएफ सेंटर, पुणे',
    'doctor.p1.start': 'बेबीजेन आईवीएफ के केंद्र में डॉ. भावना शर्मा की प्रेरक सोच है, जो एक कुशल और समर्पित आईवीएफ विशेषज्ञ हैं और जिनके पास',
    'doctor.p1.h1': '20 वर्षों से अधिक का अनुभव',
    'doctor.p1.mid1': 'है। उनकी यात्रा प्रतिष्ठित',
    'doctor.p1.h2': 'मौलाना आज़ाद मेडिकल कॉलेज (MAMC), दिल्ली विश्वविद्यालय',
    'doctor.p1.mid2': 'से शुरू हुई, जहां उन्होंने',
    'doctor.p1.h3': 'एमबीबीएस और डीजीओ',
    'doctor.p2.start': 'उत्कृष्टता की खोज उन्हें यूरोप ले गई, जहां उन्होंने उन्नत प्रशिक्षण प्राप्त किया, जिसमें',
    'doctor.p2.h1': 'लांडेस-फ्राउएन-उंड किंडरक्लिनिक, लिंज़',
    'doctor.p2.mid1': 'में परिष्कृत प्रशिक्षण,',
    'doctor.p2.h2': 'असिस्टेड रिप्रोडक्टिव टेक्नोलॉजी (ART) में मास्टर्स कोर्स',
    'doctor.p2.mid2': 'और',
    'doctor.p2.h3': 'कील यूनिवर्सिटी, जर्मनी से डिप्लोमा इन पेल्विक एंडोस्कोपी',
    'doctor.p3.start': 'अंतरराष्ट्रीय अनुभव के साथ, डॉ. शर्मा ने',
    'doctor.p3.h1': 'ग्वालियर में कल्याण आईवीएफ सेंटर',
    'doctor.p3.mid1': 'की शुरुआत की और अभिभावक बनने का सपना देखने वाले दंपतियों को आशा दी। उन्होंने',
    'doctor.p3.h2': '10,000 से अधिक आईवीएफ और आईसीएसआई प्रक्रियाएं',
    'doctor.p3.mid2': 'की हैं, जिनसे',
    'doctor.p3.h3': '8,000 से अधिक सफल आईवीएफ गर्भधारण',
    'doctor.p3.end': 'हुए हैं, जहां विज्ञान और संवेदनशील देखभाल का संतुलन है।',
    'doctor.p4.start': 'बेबीजेन आईवीएफ एक नया अध्याय शुरू करता है, जहां डॉ. शर्मा अपनी विशेषज्ञता',
    'doctor.p4.h1': 'पुणे और गुरुग्राम',
    'doctor.p4.mid1': 'तक ले जा रही हैं, जिन केंद्रों में अत्याधुनिक एम्ब्रायोलॉजी लैब, उन्नत डायग्नोस्टिक्स और',
    'doctor.p4.h2': 'आईवीएफ, आईसीएसआई, एग फ्रीजिंग और फर्टिलिटी प्रिजर्वेशन',
    'doctor.p4.end': 'जैसी नवीनतम सुविधाएं उपलब्ध हैं, ताकि इच्छुक माता-पिता को व्यक्तिगत देखभाल और उत्कृष्ट परिणाम मिल सकें।',
    'doctor.cta': 'अपॉइंटमेंट बुक करें',
    'hero.title': 'माता-पिता बनने का सपना?',
    'hero.subtitle': 'उन्नत आईवीएफ देखभाल के साथ आपकी यात्रा यहीं से शुरू होती है',
    'hero.badge': 'विशेष ऑफर',
    'hero.bookAppointment': 'अपॉइंटमेंट बुक करें',
    'hero.selectService': 'सेवा चुनें',
    'hero.service.ivf': 'आईवीएफ उपचार',
    'hero.service.consultation': 'परामर्श',
    'hero.service.gynaecologist': 'स्त्री रोग विशेषज्ञ',
    'hero.input.name': 'आपका नाम',
    'hero.input.email': 'ईमेल पता (वैकल्पिक)',
    'hero.input.phone': 'फोन नंबर',
    'hero.requestCallback': 'कॉलबैक का अनुरोध करें',
    'hero.status.sending': 'आपका अनुरोध भेजा जा रहा है...',
    'hero.status.success': 'अनुरोध सफलतापूर्वक भेज दिया गया! हम जल्द ही आपसे संपर्क करेंगे।',
    'hero.status.failed': 'अनुरोध भेजने में विफल। कृपया फिर से प्रयास करें।',
    'header.nav.doctors': 'डॉक्टर्स',
    'header.nav.centers': 'फर्टिलिटी सेंटर्स',
    'header.nav.stories': 'वेब स्टोरीज़',
    'common.bookAppointment': 'अपॉइंटमेंट बुक करें',
    'common.submit': 'सबमिट करें',
    'common.offerLine': 'Rs. 40000 तक बचत। केवल 3 स्लॉट बचे हैं!!',
    'common.saveUpto': 'Rs. 40000 तक बचत',
    'common.slotsLeft': 'केवल 3 स्लॉट बचे हैं!!',
    'common.callUs': 'कॉल करें',
    'common.bookConsultation': 'कंसल्टेशन बुक करें',
    'common.chatWhatsapp': 'WhatsApp पर चैट करें',
    'common.callNow': 'अभी कॉल करें',
    'hero.mainHeadingTop': 'आपकी यात्रा',
    'hero.mainHeadingBottom': 'मातृत्व-पितृत्व की ओर यहीं से शुरू होती है',
    'hero.description': 'उन्नत फर्टिलिटी केयर जो आपके मातृत्व-पितृत्व की हर चरण में सहायता करती है—दवाइयों से लेकर IVF और ICSI जैसी उन्नत प्रक्रियाओं तक, अनुभवी विशेषज्ञों के मार्गदर्शन के साथ।',
    'hero.form.heading': 'पर्सनलाइज्ड कंसल्टेशन पाएं!',
    'hero.form.tcPrefix': 'आगे बढ़कर आप हमारी',
    'hero.form.tc': 'शर्तों',
    'hero.form.and': 'और',
    'hero.form.privacy': 'प्राइवेसी पॉलिसी',
    'hero.form.whatsappOptin': 'WhatsApp अपडेट्स के लिए ऑप्ट-इन',
    'hero.stats.babies': 'IVF से जन्मे शिशु',
    'hero.stats.cities': 'भारत के शहर',
    'hero.stats.experience': 'अनुभवी डॉक्टरों के वर्ष',
    'hero.stats.bornTillDate': 'आज तक IVF से जन्मे शिशु',
    'hero.stats.everyMonth': 'हर महीने IVF से जन्मे शिशु',
    'hero.stats.ivfExperience': 'IVF और बांझपन उपचार में वर्षों का अनुभव',
    'contact.title': 'संपर्क करें',
    'contact.subtitle': 'आज ही कंसल्टेशन का अनुरोध करें',
    'contact.input.name': 'आपका नाम',
    'contact.input.email': 'आपका ईमेल पता (वैकल्पिक)',
    'contact.input.phone': 'आपका फोन नंबर',
    'contact.submit': 'अनुरोध भेजें',
    'contact.info.phone': 'फोन',
    'contact.info.email': 'ईमेल',
    'contact.info.address': 'पता',
    'contact.info.hours': 'समय',
    'contact.info.addressValue': '2nd Floor, Kumar Prism, Amanora Park Town, Hadapsar, Pune',
    'contact.info.hoursValue': 'सोम – शनि: सुबह 9:00 – शाम 7:00',
    'doctor.expertMessage': 'आईवीएफ विशेषज्ञ संदेश',
    'doctor.stat.years': 'वर्ष',
    'doctor.stat.ivficsi': 'आईवीएफ/आईसीएसआई',
    'doctor.stat.successes': 'सफलताएं',
    'doctor.badge.years': '20+ वर्ष',
    'doctor.badge.ivficsi': 'आईवीएफ + आईसीएसआई',
    'doctor.badge.global': 'वैश्विक प्रशिक्षण',
    'marquee.title': 'हमारी टीम की IVF सफलता मीडिया में प्रकाशित',
    'gated.badge': 'मुफ़्त IVF निर्णय संसाधन',
    'gated.title': 'IVF सेंटर चुनने से पहले यह अवश्य पढ़ें',
    'gated.description': '20+ वर्षों में हमारी टीम ने 14 देशों के 8000+ दंपतियों की मदद की है। ये संसाधन आपको महंगी गलतियों से बचाकर सही निर्णय लेने में मदद करेंगे।',
    'gated.stats.couples': 'समर्थित दंपति',
    'gated.stats.countries': 'देश',
    'gated.stats.years': 'अनुभव के वर्ष',
    'gated.riskTitle': 'गलत IVF सेंटर चुनने पर क्या समस्याएँ होती हैं?',
    'gated.verifyTitle': 'IVF शुरू करने से पहले क्या सत्यापित करें?',
    'gated.risk1': 'अनुभवहीन डॉक्टर और एम्ब्रायोलॉजिस्ट सफलता दर घटा सकते हैं।',
    'gated.risk2': 'कमज़ोर लैब इंफ्रास्ट्रक्चर भ्रूण की गुणवत्ता और परिणाम प्रभावित करता है।',
    'gated.risk3': 'कम गुणवत्ता की सामग्री उपचार की प्रभावशीलता घटा सकती है।',
    'gated.risk4': 'इंजेक्शन, टेस्ट और प्रक्रियाओं के छिपे खर्च बाद में जोड़े जाते हैं।',
    'gated.verify1': 'सिर्फ मार्केटिंग नहीं, उम्र और केस-आधारित सफलता डेटा मांगें।',
    'gated.verify2': 'उपचार शुरू करने से पहले सभी मुख्य खर्च लिखित में लें।',
    'gated.verify3': 'सुनिश्चित करें कि सेंटर में IVF + ICSI + फ्रीजिंग की पूर्ण सुविधा हो।',
    'gated.verify4': 'सत्यापित करें कि पूरा चक्र वही विशेषज्ञ संभालेंगे।',
    'gated.resourceLabel': 'संसाधन',
    'gated.resource1.title': '5 गलतियाँ जो IVF सफलता की संभावना कम करती हैं',
    'gated.resource1.desc': 'समय और परिणाम खराब करने वाले सामान्य निर्णयों से बचें।',
    'gated.resource1.cta': 'यह गाइड अनलॉक करें',
    'gated.resource2.title': 'पुणे में IVF चुनते समय लोगों को होने वाली 7 समस्याएँ',
    'gated.resource2.desc': 'रेड फ्लैग्स जल्दी पहचानें और पारदर्शी सेंटर चुनें।',
    'gated.resource2.cta': 'निर्णय से पहले पढ़ें',
    'gated.resource3.title': 'IVF शुरू करने से पहले पूछे जाने वाले ज़रूरी सवाल',
    'gated.resource3.desc': 'पहली कंसल्टेशन में इस चेकलिस्ट से केंद्रों की सही तुलना करें।',
    'gated.resource3.cta': 'प्रश्न सूची पाएं',
    'gated.helpTitle': 'जल्दी निर्णय में मदद चाहिए?',
    'gated.helpDesc': 'हमारे IVF काउंसलर से बात करें और पर्सनलाइज्ड ट्रीटमेंट रोडमैप पाएं।',
    'gated.bookFree': 'फ्री कंसल्टेशन बुक करें',
    'videos.badge': 'वास्तविक मरीज यात्राएँ',
    'videos.title': 'IVF सफलता की कहानियाँ',
    'videos.subtitle': 'देखें कैसे वास्तविक परिवारों ने अपने उपचार अनुभव और परिणाम साझा किए।',
    'videos.scrollLeft': 'बाएँ स्क्रॉल करें',
    'videos.scrollRight': 'दाएँ स्क्रॉल करें',
    'videos.realStory': 'वास्तविक कहानी',
    'videos.likeStory': 'कहानी पसंद करें',
    'videos.shareStory': 'कहानी साझा करें',
    'videos.swipeHint': 'और कहानियाँ देखने के लिए स्वाइप करें',
    'videos.title1': '8 साल की उम्मीद के बाद',
    'videos.title2': 'हमारा पहला पॉज़िटिव परिणाम',
    'videos.title3': 'विश्वसनीय टीम, बेहतर सफर',
    'videos.title4': 'संदेह से मातृत्व-पितृत्व तक',
    'videos.title5': 'हाई-रिस्क केस, खुशहाल परिणाम',
    'videos.treatment1': 'आईवीएफ + आईसीएसआई',
    'videos.treatment2': 'आईवीएफ',
    'videos.treatment3': 'कंसल्टेशन + आईवीएफ',
    'videos.treatment4': 'आईवीएफ + एम्ब्रियो ट्रांसफर',
    'videos.treatment5': 'उन्नत फर्टिलिटी केयर',
    'videos.views1': '15.4K व्यूज़',
    'videos.views2': '7.4K व्यूज़',
    'videos.views3': '5.3K व्यूज़',
    'videos.views4': '27.5K व्यूज़',
    'videos.views5': '13.6K व्यूज़',
    'cert.badge': 'प्रमाणित उत्कृष्टता',
    'cert.title': 'प्रमाणपत्र और संबद्धताएँ',
    'cert.subtitle': 'हमारा केंद्र मेडिकल सुरक्षा और नैतिक मानकों के उच्चतम अंतरराष्ट्रीय मानकों का पालन करता है।',
    'cert.card1': 'मेडिकल मान्यता',
    'cert.card2': 'आईवीएफ विशेषज्ञता',
    'cert.card3': 'क्लिनिकल उत्कृष्टता',
    'cert.card4': 'अंतरराष्ट्रीय मानक',
    'cert.card5': 'लैब प्रमाणन',
    'cert.card6': 'गुणवत्ता आश्वासन',
    'cert.card7': 'हेल्थकेयर अनुपालन',
    'cert.card8': 'सेफ्टी प्रोटोकॉल',
    'cert.card9': 'उन्नत एम्ब्रायोलॉजी',
    'cert.card10': 'प्रोफेशनल संबद्धता',
    'cert.card11': 'मरीज देखभाल पुरस्कार',
    'cert.card12': 'आईवीएफ में नवाचार',
    'cert.badge1': 'ICMR पंजीकृत',
    'cert.badge2': 'ISO प्रमाणित',
    'cert.badge3': 'ISAR संबद्ध',
    'footer.about': 'Babygen IVF की टीम ने हजारों निसंतान दंपतियों को स्वस्थ शिशु का सपना पूरा करने में मदद की है। हमारे डॉक्टर और काउंसलर हर कदम पर साथ रहते हैं।',
    'footer.contactTitle': 'संपर्क करें',
    'footer.linksTitle': 'महत्वपूर्ण लिंक',
    'footer.link.about': 'हमारे बारे में',
    'footer.link.privacy': 'प्राइवेसी पॉलिसी',
    'footer.link.disclaimer': 'अस्वीकरण',
    'footer.link.contact': 'संपर्क करें',
    'footer.address': '2nd Floor, Kumar Prism, Amanora Park Town, Hadapsar, Pune',
    'footer.copyright': '© 2026 Babygen IVF, Pune. सर्वाधिकार सुरक्षित।',
    'thankyou.badge': 'सबमिशन कन्फर्म',
    'thankyou.title': 'संपर्क करने के लिए धन्यवाद',
    'thankyou.subtitle': 'आपका अनुरोध सफलतापूर्वक प्राप्त हुआ। हमारी फर्टिलिटी टीम जल्द ही आपसे अगले कदमों के लिए संपर्क करेगी।',
    'thankyou.call': 'कॉल: 731 485 5000',
    'thankyou.whatsapp': 'WhatsApp पर आगे बढ़ें',
    'thankyou.card1.title': 'अगला क्या होगा?',
    'thankyou.card1.desc': 'हमारे कोऑर्डिनेटर आपका केस समझकर कंसल्टेशन शेड्यूल करेंगे।',
    'thankyou.card2.title': 'अपना स्लॉट सुरक्षित रखें',
    'thankyou.card2.desc': 'बुकिंग में देरी से बचने के लिए WhatsApp पर अपनी पसंदीदा कॉल टाइम साझा करें।',
    'thankyou.card3.title': 'ऑफर रिमाइंडर',
    'thankyou.card3.desc': 'योग्य उपचार योजनाओं पर आप Rs. 40000 तक बचत कर सकते हैं।',
    'thankyou.backHome': 'होम पर वापस जाएँ',
    'notfound.message': 'उफ़! पेज नहीं मिला',
    'notfound.backHome': 'होम पर वापस जाएँ',
    'lang.english': 'अंग्रेज़ी',
    'lang.hindi': 'हिंदी',
    'lang.marathi': 'मराठी',
  },
  mr: {
    'header.nav.home': 'मुख्यपृष्ठ',
    'header.nav.services': 'सेवा',
    'header.nav.whyUs': 'आम्हालाच का',
    'header.nav.ourTeam': 'आमची टीम',
    'header.nav.gallery': 'गॅलरी',
    'header.nav.successStories': 'यशोगाथा',
    'header.nav.blog': 'ब्लॉग',
    'header.nav.contactUs': 'संपर्क',
    'header.address.line1': '2nd floor, Kumar Prism, Road, above Yes Bank',
    'header.address.line2': 'opp. Fab India, Kirtane Baug, Amanora Park Town, Hadapsar, Pune',
    'header.bookAppointment': 'अपॉइंटमेंट बुक करा',
    'header.hospitalName': 'बेबीजेन आयव्हीएफ सेंटर',
    'header.location': 'पुणे',
    'header.location2': 'गुरुग्राम',
    'header.serviceDetails': 'सेवा तपशील',
    'header.viewAll': 'सर्व पहा',
    'doctor.name': 'डॉ. भावना शर्मा',
    'doctor.position': 'एमबीबीएस, डीजीओ | आयव्हीएफ व वंध्यत्व तज्ञ',
    'doctor.heading.prefix': 'संदेश',
    'doctor.heading.name': 'डॉ. भावना शर्मा यांचा',
    'doctor.subtitle': 'आयव्हीएफ तज्ञ, बेबीजेन आयव्हीएफ सेंटर, पुणे',
    'doctor.p1.start': 'बेबीजेन आयव्हीएफच्या केंद्रस्थानी डॉ. भावना शर्मा यांची प्रेरणादायी दृष्टी आहे; त्या कुशल व समर्पित आयव्हीएफ तज्ञ असून त्यांना',
    'doctor.p1.h1': '20 वर्षांहून अधिक अनुभव',
    'doctor.p1.mid1': 'आहे. त्यांचा प्रवास प्रतिष्ठित',
    'doctor.p1.h2': 'मौलाना आझाद मेडिकल कॉलेज (MAMC), दिल्ली विद्यापीठ',
    'doctor.p1.mid2': 'येथून सुरू झाला, जिथे त्यांनी',
    'doctor.p1.h3': 'एमबीबीएस व डीजीओ',
    'doctor.p2.start': 'उत्कृष्टतेच्या ध्यासाने त्यांनी युरोपमध्ये प्रगत शिक्षण घेतले, ज्यात',
    'doctor.p2.h1': 'लांडेस-फ्राउएन-उंड किंडरक्लिनिक, लिंझ',
    'doctor.p2.mid1': 'येथील सखोल प्रशिक्षण,',
    'doctor.p2.h2': 'असिस्टेड रिप्रोडक्टिव टेक्नॉलॉजी (ART) मधील मास्टर्स कोर्स',
    'doctor.p2.mid2': 'आणि',
    'doctor.p2.h3': 'कील युनिव्हर्सिटी, जर्मनी येथील डिप्लोमा इन पेल्विक एंडोस्कोपी',
    'doctor.p3.start': 'समृद्ध आंतरराष्ट्रीय अनुभवासह, डॉ. शर्मा यांनी',
    'doctor.p3.h1': 'ग्वालियरमध्ये कल्याण आयव्हीएफ सेंटर',
    'doctor.p3.mid1': 'सुरू करून पालकत्वाचे स्वप्न पाहणाऱ्या जोडप्यांना आशा दिली. त्यांनी',
    'doctor.p3.h2': '10,000 पेक्षा जास्त आयव्हीएफ आणि आयसीएसआय प्रक्रिया',
    'doctor.p3.mid2': 'केल्या असून',
    'doctor.p3.h3': '8,000 पेक्षा अधिक यशस्वी आयव्हीएफ गर्भधारणा',
    'doctor.p3.end': 'घडवून आणल्या, जिथे विज्ञानासोबत करुणामय सेवेलाही समान महत्त्व आहे.',
    'doctor.p4.start': 'बेबीजेन आयव्हीएफ एक नवे पर्व सुरू करते, ज्यात डॉ. शर्मा आपले कौशल्य',
    'doctor.p4.h1': 'पुणे आणि गुरुग्राम',
    'doctor.p4.mid1': 'येथे विस्तारत आहेत, जिथे अत्याधुनिक एम्ब्रायोलॉजी लॅब्स, प्रगत निदान आणि',
    'doctor.p4.h2': 'आयव्हीएफ, आयसीएसआय, एग फ्रीझिंग आणि फर्टिलिटी प्रिझर्व्हेशन',
    'doctor.p4.end': 'सारख्या नवीन तंत्रज्ञानासह इच्छुक पालकांसाठी वैयक्तिकृत काळजी आणि उत्कृष्ट परिणाम दिले जातात.',
    'doctor.cta': 'अपॉइंटमेंट बुक करा',
    'hero.title': 'पालकत्वाचे स्वप्न पाहताय?',
    'hero.subtitle': 'प्रगत आयव्हीएफ केअरसह तुमची वाटचाल इथून सुरू होते',
    'hero.badge': 'विशेष ऑफर',
    'hero.bookAppointment': 'अपॉइंटमेंट बुक करा',
    'hero.selectService': 'सेवा निवडा',
    'hero.service.ivf': 'आयव्हीएफ उपचार',
    'hero.service.consultation': 'सल्लामसलत',
    'hero.service.gynaecologist': 'स्त्रीरोगतज्ज्ञ',
    'hero.input.name': 'तुमचे नाव',
    'hero.input.email': 'ईमेल पत्ता (ऐच्छिक)',
    'hero.input.phone': 'फोन नंबर',
    'hero.requestCallback': 'कॉलबॅकची विनंती करा',
    'hero.status.sending': 'तुमची विनंती पाठवली जात आहे...',
    'hero.status.success': 'विनंती यशस्वीरीत्या पाठवली! आम्ही लवकरच संपर्क करू.',
    'hero.status.failed': 'विनंती पाठवण्यात अयशस्वी. कृपया पुन्हा प्रयत्न करा.',
    'header.nav.doctors': 'डॉक्टर्स',
    'header.nav.centers': 'फर्टिलिटी सेंटर्स',
    'header.nav.stories': 'वेब स्टोरीज',
    'common.bookAppointment': 'अपॉइंटमेंट बुक करा',
    'common.submit': 'सबमिट करा',
    'common.offerLine': 'Rs. 40000 पर्यंत बचत. फक्त 3 स्लॉट शिल्लक!!',
    'common.saveUpto': 'Rs. 40000 पर्यंत बचत',
    'common.slotsLeft': 'फक्त 3 स्लॉट शिल्लक!!',
    'common.callUs': 'आम्हाला कॉल करा',
    'common.bookConsultation': 'कन्सल्टेशन बुक करा',
    'common.chatWhatsapp': 'WhatsApp वर चॅट करा',
    'common.callNow': 'आत्ताच कॉल करा',
    'hero.mainHeadingTop': 'तुमचा प्रवास',
    'hero.mainHeadingBottom': 'पालकत्वाकडे इथूनच सुरू होतो',
    'hero.description': 'प्रगत फर्टिलिटी केअर जी पालकत्वाच्या प्रत्येक टप्प्यावर साथ देते—औषधोपचारांपासून IVF आणि ICSI सारख्या प्रगत प्रक्रियांपर्यंत, अनुभवी तज्ञांच्या मार्गदर्शनासह.',
    'hero.form.heading': 'वैयक्तिकृत कन्सल्टेशन मिळवा!',
    'hero.form.tcPrefix': 'पुढे जाऊन तुम्ही आमच्या',
    'hero.form.tc': 'अटी',
    'hero.form.and': 'आणि',
    'hero.form.privacy': 'गोपनीयता धोरणांशी',
    'hero.form.whatsappOptin': 'WhatsApp अपडेट्ससाठी ऑप्ट-इन',
    'hero.stats.babies': 'IVF द्वारे जन्मलेली बाळे',
    'hero.stats.cities': 'भारतामधील शहरे',
    'hero.stats.experience': 'अनुभवी डॉक्टरांचा अनुभव',
    'hero.stats.bornTillDate': 'आजपर्यंत IVF द्वारे जन्मलेली बाळे',
    'hero.stats.everyMonth': 'दर महिन्याला IVF द्वारे जन्मलेली बाळे',
    'hero.stats.ivfExperience': 'IVF आणि वंध्यत्व उपचारातील वर्षांचा अनुभव',
    'contact.title': 'आमच्याशी संपर्क साधा',
    'contact.subtitle': 'आजच कन्सल्टेशनची विनंती करा',
    'contact.input.name': 'तुमचे नाव',
    'contact.input.email': 'तुमचा ईमेल पत्ता (ऐच्छिक)',
    'contact.input.phone': 'तुमचा फोन नंबर',
    'contact.submit': 'विनंती पाठवा',
    'contact.info.phone': 'फोन',
    'contact.info.email': 'ईमेल',
    'contact.info.address': 'पत्ता',
    'contact.info.hours': 'वेळ',
    'contact.info.addressValue': '2nd Floor, Kumar Prism, Amanora Park Town, Hadapsar, Pune',
    'contact.info.hoursValue': 'सोम – शनि: सकाळी 9:00 – संध्याकाळी 7:00',
    'doctor.expertMessage': 'आयव्हीएफ तज्ञांचा संदेश',
    'doctor.stat.years': 'वर्षे',
    'doctor.stat.ivficsi': 'आयव्हीएफ/आयसीएसआय',
    'doctor.stat.successes': 'यशस्वी परिणाम',
    'doctor.badge.years': '20+ वर्षे',
    'doctor.badge.ivficsi': 'आयव्हीएफ + आयसीएसआय',
    'doctor.badge.global': 'जागतिक प्रशिक्षण',
    'marquee.title': 'आमच्या टीमच्या IVF यशकथा माध्यमांत झळकल्या',
    'gated.badge': 'मोफत IVF निर्णय मार्गदर्शक',
    'gated.title': 'IVF सेंटर निवडण्यापूर्वी हे नक्की वाचा',
    'gated.description': '20+ वर्षांत आमच्या टीमने 14 देशांतील 8000+ जोडप्यांना मदत केली आहे. हे संसाधन तुम्हाला महागड्या चुका टाळून योग्य निर्णय घ्यायला मदत करतात.',
    'gated.stats.couples': 'मदत केलेली जोडपी',
    'gated.stats.countries': 'देश',
    'gated.stats.years': 'अनुभवाची वर्षे',
    'gated.riskTitle': 'चुकीचे IVF सेंटर निवडल्यास काय बिघडू शकते?',
    'gated.verifyTitle': 'IVF सुरू करण्यापूर्वी काय तपासावे?',
    'gated.risk1': 'अनुभवहीन डॉक्टर आणि एम्ब्रायोलॉजिस्ट यशदर कमी करू शकतात.',
    'gated.risk2': 'कमकुवत लॅब सुविधा भ्रूण गुणवत्ता आणि परिणामांवर परिणाम करतात.',
    'gated.risk3': 'निकृष्ट दर्जाच्या साहित्यामुळे उपचाराची प्रभावीता कमी होऊ शकते.',
    'gated.risk4': 'इंजेक्शन, टेस्ट आणि प्रक्रियांसाठी लपवलेले खर्च नंतर जोडले जातात.',
    'gated.verify1': 'फक्त मार्केटिंग नव्हे, वय आणि केस-आधारित यशदर मागा.',
    'gated.verify2': 'उपचार सुरू करण्यापूर्वी सर्व प्रमुख खर्च लिखित स्वरूपात घ्या.',
    'gated.verify3': 'सेंटरमध्ये IVF + ICSI + फ्रीझिंगची पूर्ण सुविधा आहे का ते तपासा.',
    'gated.verify4': 'संपूर्ण सायकल तोच तज्ञ सांभाळणार का ते खात्री करा.',
    'gated.resourceLabel': 'संसाधन',
    'gated.resource1.title': 'IVF यश कमी करणाऱ्या 5 चुका',
    'gated.resource1.desc': 'वेळ आणि परिणाम दोन्हीवर परिणाम करणाऱ्या सामान्य चुका टाळा.',
    'gated.resource1.cta': 'ही मार्गदर्शिका अनलॉक करा',
    'gated.resource2.title': 'पुण्यात IVF निवडताना लोकांना येणाऱ्या 7 समस्या',
    'gated.resource2.desc': 'लाल झेंडे लवकर ओळखा आणि पारदर्शक सेंटर निवडा.',
    'gated.resource2.cta': 'निर्णयापूर्वी वाचा',
    'gated.resource3.title': 'IVF सुरू करण्यापूर्वी विचारायचे महत्त्वाचे प्रश्न',
    'gated.resource3.desc': 'पहिल्या कन्सल्टेशनमध्ये या चेकलिस्टने योग्य तुलना करा.',
    'gated.resource3.cta': 'प्रश्नांची यादी मिळवा',
    'gated.helpTitle': 'लवकर निर्णयासाठी मदत हवी आहे?',
    'gated.helpDesc': 'आमच्या IVF समुपदेशकाशी बोला आणि वैयक्तिकृत उपचार रोडमॅप मिळवा.',
    'gated.bookFree': 'मोफत कन्सल्टेशन बुक करा',
    'videos.badge': 'खऱ्या रुग्णांच्या प्रवासकथा',
    'videos.title': 'IVF यशकथा',
    'videos.subtitle': 'खऱ्या कुटुंबांनी त्यांचा उपचार प्रवास आणि अनुभव कसा सांगितला ते पाहा.',
    'videos.scrollLeft': 'डावीकडे स्क्रोल करा',
    'videos.scrollRight': 'उजवीकडे स्क्रोल करा',
    'videos.realStory': 'खरी कथा',
    'videos.likeStory': 'कथा पसंत करा',
    'videos.shareStory': 'कथा शेअर करा',
    'videos.swipeHint': 'अधिक कथा पाहण्यासाठी स्वाइप करा',
    'videos.title1': '8 वर्षांच्या आशेनंतर',
    'videos.title2': 'आमचा पहिला पॉझिटिव्ह परिणाम',
    'videos.title3': 'विश्वासू टीम, चांगला प्रवास',
    'videos.title4': 'संशयातून पालकत्वापर्यंत',
    'videos.title5': 'हाय-रिस्क केस, आनंदी शेवट',
    'videos.treatment1': 'आयव्हीएफ + आयसीएसआय',
    'videos.treatment2': 'आयव्हीएफ',
    'videos.treatment3': 'कन्सल्टेशन + आयव्हीएफ',
    'videos.treatment4': 'आयव्हीएफ + भ्रूण हस्तांतरण',
    'videos.treatment5': 'प्रगत फर्टिलिटी केअर',
    'videos.views1': '15.4K व्ह्यूज',
    'videos.views2': '7.4K व्ह्यूज',
    'videos.views3': '5.3K व्ह्यूज',
    'videos.views4': '27.5K व्ह्यूज',
    'videos.views5': '13.6K व्ह्यूज',
    'cert.badge': 'प्रमाणित उत्कृष्टता',
    'cert.title': 'प्रमाणपत्रे आणि संलग्नता',
    'cert.subtitle': 'आमचे केंद्र वैद्यकीय सुरक्षा आणि नैतिकतेच्या सर्वोच्च आंतरराष्ट्रीय मानकांचे पालन करते.',
    'cert.card1': 'वैद्यकीय मान्यता',
    'cert.card2': 'आयव्हीएफ विशेषीकरण',
    'cert.card3': 'क्लिनिकल उत्कृष्टता',
    'cert.card4': 'आंतरराष्ट्रीय मानके',
    'cert.card5': 'लॅब प्रमाणन',
    'cert.card6': 'गुणवत्ता हमी',
    'cert.card7': 'हेल्थकेअर अनुपालन',
    'cert.card8': 'सुरक्षा प्रोटोकॉल',
    'cert.card9': 'प्रगत एम्ब्रायोलॉजी',
    'cert.card10': 'व्यावसायिक संलग्नता',
    'cert.card11': 'रुग्णसेवा पुरस्कार',
    'cert.card12': 'IVF मधील नवोपक्रम',
    'cert.badge1': 'ICMR नोंदणीकृत',
    'cert.badge2': 'ISO प्रमाणित',
    'cert.badge3': 'ISAR संलग्न',
    'footer.about': 'Babygen IVF टीमने हजारो नि:संतान जोडप्यांना निरोगी बाळाचे स्वप्न पूर्ण करण्यात मदत केली आहे. आमचे डॉक्टर आणि समुपदेशक प्रत्येक टप्प्यावर साथ देतात.',
    'footer.contactTitle': 'संपर्क करा',
    'footer.linksTitle': 'महत्वाचे दुवे',
    'footer.link.about': 'आमच्याबद्दल',
    'footer.link.privacy': 'गोपनीयता धोरण',
    'footer.link.disclaimer': 'अस्वीकरण',
    'footer.link.contact': 'संपर्क करा',
    'footer.address': '2nd Floor, Kumar Prism, Amanora Park Town, Hadapsar, Pune',
    'footer.copyright': '© 2026 Babygen IVF, Pune. सर्व हक्क राखीव.',
    'thankyou.badge': 'सबमिशन कन्फर्म झाले',
    'thankyou.title': 'संपर्क केल्याबद्दल धन्यवाद',
    'thankyou.subtitle': 'तुमची विनंती यशस्वीरीत्या प्राप्त झाली आहे. आमची फर्टिलिटी टीम पुढील टप्प्यांसाठी लवकरच संपर्क करेल.',
    'thankyou.call': 'कॉल: 731 485 5000',
    'thankyou.whatsapp': 'WhatsApp वर पुढे जा',
    'thankyou.card1.title': 'पुढे काय होईल?',
    'thankyou.card1.desc': 'आमचे समन्वयक तुमचा केस समजून कन्सल्टेशन निश्चित करतील.',
    'thankyou.card2.title': 'तुमचा स्लॉट राखून ठेवा',
    'thankyou.card2.desc': 'बुकिंग उशीर टाळण्यासाठी WhatsApp वर पसंतीची कॉल वेळ सांगा.',
    'thankyou.card3.title': 'ऑफर स्मरणपत्र',
    'thankyou.card3.desc': 'पात्र उपचार योजनांवर तुम्ही Rs. 40000 पर्यंत बचत करू शकता.',
    'thankyou.backHome': 'मुख्यपृष्ठावर जा',
    'notfound.message': 'अरेरे! पृष्ठ सापडले नाही',
    'notfound.backHome': 'मुख्यपृष्ठावर परत जा',
    'lang.english': 'इंग्रजी',
    'lang.hindi': 'हिंदी',
    'lang.marathi': 'मराठी',
  },
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage,
      t: (key: string) => translations[language][key] ?? translations.en[key] ?? key,
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = (): LanguageContextValue => {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }

  return context;
};
