import React, { createContext, useContext, useMemo, useState } from 'react';

type Language = 'en' | 'hi' | 'mr';

type TranslationDictionary = Record<string, string>;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const translations: Record<Language, TranslationDictionary> = {
  en: {
    'header.nav.home': 'Home',
    'header.nav.services': 'Services',
    'header.nav.whyUs': 'Why Us',
    'header.nav.ourTeam': 'Our Team',
    'header.nav.gallery': 'Gallery',
    'header.nav.successStories': 'Success Stories',
    'header.nav.blog': 'Blog',
    'header.nav.contactUs': 'Contact Us',
    'header.address.line1': '2nd floor, Kumar Prism, Road, above Yes Bank',
    'header.address.line2': 'opp. Fab India, Kirtane Baug, Amanora Park Town, Hadapsar, Pune',
    'header.bookAppointment': 'Book an Appointment',
    'header.hospitalName': 'Babygen IVF Centre',
    'header.location': 'Pune',
    'header.location2': 'Gurugram',
    'header.serviceDetails': 'Service Details',
    'header.viewAll': 'View All',
    'doctor.name': 'Dr. Bhavna Sharma',
    'doctor.position': 'MBBS, DGO | IVF & Infertility Specialist',
    'doctor.heading.prefix': 'A Message from',
    'doctor.heading.name': 'Dr. Bhavna Sharma',
    'doctor.subtitle': 'IVF Specialist, Babygen IVF Centre, Pune',
    'doctor.p1.start': 'At the heart of Babygen IVF lies a passionate vision brought to life by Dr. Bhavna Sharma, a dexterous and dedicated IVF specialist with',
    'doctor.p1.h1': 'more than 20 years of experience',
    'doctor.p1.mid1': '. Her journey began at the prestigious',
    'doctor.p1.h2': 'Maulana Azad Medical College (MAMC), Delhi University',
    'doctor.p1.mid2': ', where she completed her',
    'doctor.p1.h3': 'MBBS and DGO',
    'doctor.p2.start': 'Her pursuit of excellence took her to Europe for advanced learning, including refined training at',
    'doctor.p2.h1': 'Landes-Frauen-Und Kinderklinik, Linz',
    'doctor.p2.mid1': ', a',
    'doctor.p2.h2': 'Masters course in Assisted Reproductive Technology (ART)',
    'doctor.p2.mid2': ', and a',
    'doctor.p2.h3': 'Diploma in Pelvic Endoscopy from Kiel University, Germany',
    'doctor.p3.start': 'With rich international exposure, Dr. Sharma pioneered',
    'doctor.p3.h1': 'Kalyan IVF Centre in Gwalior',
    'doctor.p3.mid1': ', bringing hope to couples dreaming of parenthood. She has performed',
    'doctor.p3.h2': 'over 10,000 IVF and ICSI procedures',
    'doctor.p3.mid2': ', resulting in',
    'doctor.p3.h3': 'more than 8,000 successful IVF pregnancies',
    'doctor.p3.end': ', blending science with compassionate care.',
    'doctor.p4.start': 'Babygen IVF opens a new chapter as Dr. Sharma extends her expertise to',
    'doctor.p4.h1': 'Pune and Gurugram',
    'doctor.p4.mid1': ', with centres equipped with cutting-edge embryology labs, advanced diagnostics, and the latest innovations in',
    'doctor.p4.h2': 'IVF, ICSI, egg freezing, and fertility preservation',
    'doctor.p4.end': 'ensuring personalized care and excellent outcomes for aspiring parents.',
    'doctor.cta': 'Book an Appointment',
    'hero.title': 'Dreaming of Parenthood?',
    'hero.subtitle': 'Your Journey Begins Here With Advanced IVF Care',
    'hero.badge': 'Special Offer',
    'hero.bookAppointment': 'Book Appointment',
    'hero.selectService': 'Select Service',
    'hero.service.ivf': 'IVF Treatment',
    'hero.service.consultation': 'Consultation',
    'hero.service.gynaecologist': 'Gynaecologist',
    'hero.input.name': 'Your Name',
    'hero.input.email': 'Email Address (Optional)',
    'hero.input.phone': 'Phone Number',
    'hero.requestCallback': 'Request Callback',
    'hero.status.sending': 'Sending your request...',
    'hero.status.success': 'Request sent successfully! We will contact you shortly.',
    'hero.status.failed': 'Failed to send request. Please try again.',
    'lang.english': 'English',
    'lang.hindi': 'Hindi',
    'lang.marathi': 'Marathi',
  },
  hi: {
    'header.nav.home': 'होम',
    'header.nav.services': 'सेवाएं',
    'header.nav.whyUs': 'हमें क्यों चुनें',
    'header.nav.ourTeam': 'हमारी टीम',
    'header.nav.gallery': 'गैलरी',
    'header.nav.successStories': 'सफलता की कहानियां',
    'header.nav.blog': 'ब्लॉग',
    'header.nav.contactUs': 'संपर्क करें',
    'header.address.line1': '2nd floor, Kumar Prism, Road, above Yes Bank',
    'header.address.line2': 'opp. Fab India, Kirtane Baug, Amanora Park Town, Hadapsar, Pune',
    'header.bookAppointment': 'अपॉइंटमेंट बुक करें',
    'header.hospitalName': 'Babygen IVF Centre',
    'header.location': 'पुणे',
    'header.location2': 'गुरुग्राम',
    'header.serviceDetails': 'सेवा विवरण',
    'header.viewAll': 'सभी देखें',
    'doctor.name': 'डॉ. भावना शर्मा',
    'doctor.position': 'एमबीबीएस, डीजीओ | आईवीएफ एवं बांझपन विशेषज्ञ',
    'doctor.heading.prefix': 'संदेश',
    'doctor.heading.name': 'डॉ. भावना शर्मा का',
    'doctor.subtitle': 'आईवीएफ विशेषज्ञ, बेबीजेन आईवीएफ सेंटर, पुणे',
    'doctor.p1.start': 'बेबीजेन आईवीएफ के केंद्र में डॉ. भावना शर्मा की प्रेरक सोच है, जो एक कुशल और समर्पित आईवीएफ विशेषज्ञ हैं और जिनके पास',
    'doctor.p1.h1': '20 वर्षों से अधिक का अनुभव',
    'doctor.p1.mid1': 'है। उनकी यात्रा प्रतिष्ठित',
    'doctor.p1.h2': 'मौलाना आज़ाद मेडिकल कॉलेज (MAMC), दिल्ली विश्वविद्यालय',
    'doctor.p1.mid2': 'से शुरू हुई, जहां उन्होंने',
    'doctor.p1.h3': 'एमबीबीएस और डीजीओ',
    'doctor.p2.start': 'उत्कृष्टता की खोज उन्हें यूरोप ले गई, जहां उन्होंने उन्नत प्रशिक्षण प्राप्त किया, जिसमें',
    'doctor.p2.h1': 'लांडेस-फ्राउएन-उंड किंडरक्लिनिक, लिंज़',
    'doctor.p2.mid1': 'में परिष्कृत प्रशिक्षण,',
    'doctor.p2.h2': 'असिस्टेड रिप्रोडक्टिव टेक्नोलॉजी (ART) में मास्टर्स कोर्स',
    'doctor.p2.mid2': 'और',
    'doctor.p2.h3': 'कील यूनिवर्सिटी, जर्मनी से डिप्लोमा इन पेल्विक एंडोस्कोपी',
    'doctor.p3.start': 'अंतरराष्ट्रीय अनुभव के साथ, डॉ. शर्मा ने',
    'doctor.p3.h1': 'ग्वालियर में कल्याण आईवीएफ सेंटर',
    'doctor.p3.mid1': 'की शुरुआत की और अभिभावक बनने का सपना देखने वाले दंपतियों को आशा दी। उन्होंने',
    'doctor.p3.h2': '10,000 से अधिक आईवीएफ और आईसीएसआई प्रक्रियाएं',
    'doctor.p3.mid2': 'की हैं, जिनसे',
    'doctor.p3.h3': '8,000 से अधिक सफल आईवीएफ गर्भधारण',
    'doctor.p3.end': 'हुए हैं, जहां विज्ञान और संवेदनशील देखभाल का संतुलन है।',
    'doctor.p4.start': 'बेबीजेन आईवीएफ एक नया अध्याय शुरू करता है, जहां डॉ. शर्मा अपनी विशेषज्ञता',
    'doctor.p4.h1': 'पुणे और गुरुग्राम',
    'doctor.p4.mid1': 'तक ले जा रही हैं, जिन केंद्रों में अत्याधुनिक एम्ब्रायोलॉजी लैब, उन्नत डायग्नोस्टिक्स और',
    'doctor.p4.h2': 'आईवीएफ, आईसीएसआई, एग फ्रीजिंग और फर्टिलिटी प्रिजर्वेशन',
    'doctor.p4.end': 'जैसी नवीनतम सुविधाएं उपलब्ध हैं, ताकि इच्छुक माता-पिता को व्यक्तिगत देखभाल और उत्कृष्ट परिणाम मिल सकें।',
    'doctor.cta': 'अपॉइंटमेंट बुक करें',
    'hero.title': 'माता-पिता बनने का सपना?',
    'hero.subtitle': 'उन्नत आईवीएफ देखभाल के साथ आपकी यात्रा यहीं से शुरू होती है',
    'hero.badge': 'विशेष ऑफर',
    'hero.bookAppointment': 'अपॉइंटमेंट बुक करें',
    'hero.selectService': 'सेवा चुनें',
    'hero.service.ivf': 'आईवीएफ उपचार',
    'hero.service.consultation': 'परामर्श',
    'hero.service.gynaecologist': 'स्त्री रोग विशेषज्ञ',
    'hero.input.name': 'आपका नाम',
    'hero.input.email': 'ईमेल पता (वैकल्पिक)',
    'hero.input.phone': 'फोन नंबर',
    'hero.requestCallback': 'कॉलबैक का अनुरोध करें',
    'hero.status.sending': 'आपका अनुरोध भेजा जा रहा है...',
    'hero.status.success': 'अनुरोध सफलतापूर्वक भेज दिया गया! हम जल्द ही आपसे संपर्क करेंगे।',
    'hero.status.failed': 'अनुरोध भेजने में विफल। कृपया फिर से प्रयास करें।',
    'lang.english': 'अंग्रेज़ी',
    'lang.hindi': 'हिंदी',
    'lang.marathi': 'मराठी',
  },
  mr: {
    'header.nav.home': 'मुख्यपृष्ठ',
    'header.nav.services': 'सेवा',
    'header.nav.whyUs': 'आम्हालाच का',
    'header.nav.ourTeam': 'आमची टीम',
    'header.nav.gallery': 'गॅलरी',
    'header.nav.successStories': 'यशोगाथा',
    'header.nav.blog': 'ब्लॉग',
    'header.nav.contactUs': 'संपर्क',
    'header.address.line1': '2nd floor, Kumar Prism, Road, above Yes Bank',
    'header.address.line2': 'opp. Fab India, Kirtane Baug, Amanora Park Town, Hadapsar, Pune',
    'header.bookAppointment': 'अपॉइंटमेंट बुक करा',
    'header.hospitalName': 'Babygen IVF Centre',
    'header.location': 'पुणे',
    'header.location2': 'गुरुग्राम',
    'header.serviceDetails': 'सेवा तपशील',
    'header.viewAll': 'सर्व पहा',
    'doctor.name': 'डॉ. भावना शर्मा',
    'doctor.position': 'एमबीबीएस, डीजीओ | आयव्हीएफ व वंध्यत्व तज्ञ',
    'doctor.heading.prefix': 'संदेश',
    'doctor.heading.name': 'डॉ. भावना शर्मा यांचा',
    'doctor.subtitle': 'आयव्हीएफ तज्ञ, बेबीजेन आयव्हीएफ सेंटर, पुणे',
    'doctor.p1.start': 'बेबीजेन आयव्हीएफच्या केंद्रस्थानी डॉ. भावना शर्मा यांची प्रेरणादायी दृष्टी आहे; त्या कुशल व समर्पित आयव्हीएफ तज्ञ असून त्यांना',
    'doctor.p1.h1': '20 वर्षांहून अधिक अनुभव',
    'doctor.p1.mid1': 'आहे. त्यांचा प्रवास प्रतिष्ठित',
    'doctor.p1.h2': 'मौलाना आझाद मेडिकल कॉलेज (MAMC), दिल्ली विद्यापीठ',
    'doctor.p1.mid2': 'येथून सुरू झाला, जिथे त्यांनी',
    'doctor.p1.h3': 'एमबीबीएस व डीजीओ',
    'doctor.p2.start': 'उत्कृष्टतेच्या ध्यासाने त्यांनी युरोपमध्ये प्रगत शिक्षण घेतले, ज्यात',
    'doctor.p2.h1': 'लांडेस-फ्राउएन-उंड किंडरक्लिनिक, लिंझ',
    'doctor.p2.mid1': 'येथील सखोल प्रशिक्षण,',
    'doctor.p2.h2': 'असिस्टेड रिप्रोडक्टिव टेक्नॉलॉजी (ART) मधील मास्टर्स कोर्स',
    'doctor.p2.mid2': 'आणि',
    'doctor.p2.h3': 'कील युनिव्हर्सिटी, जर्मनी येथील डिप्लोमा इन पेल्विक एंडोस्कोपी',
    'doctor.p3.start': 'समृद्ध आंतरराष्ट्रीय अनुभवासह, डॉ. शर्मा यांनी',
    'doctor.p3.h1': 'ग्वालियरमध्ये कल्याण आयव्हीएफ सेंटर',
    'doctor.p3.mid1': 'सुरू करून पालकत्वाचे स्वप्न पाहणाऱ्या जोडप्यांना आशा दिली. त्यांनी',
    'doctor.p3.h2': '10,000 पेक्षा जास्त आयव्हीएफ आणि आयसीएसआय प्रक्रिया',
    'doctor.p3.mid2': 'केल्या असून',
    'doctor.p3.h3': '8,000 पेक्षा अधिक यशस्वी आयव्हीएफ गर्भधारणा',
    'doctor.p3.end': 'घडवून आणल्या, जिथे विज्ञानासोबत करुणामय सेवेलाही समान महत्त्व आहे.',
    'doctor.p4.start': 'बेबीजेन आयव्हीएफ एक नवे पर्व सुरू करते, ज्यात डॉ. शर्मा आपले कौशल्य',
    'doctor.p4.h1': 'पुणे आणि गुरुग्राम',
    'doctor.p4.mid1': 'येथे विस्तारत आहेत, जिथे अत्याधुनिक एम्ब्रायोलॉजी लॅब्स, प्रगत निदान आणि',
    'doctor.p4.h2': 'आयव्हीएफ, आयसीएसआय, एग फ्रीझिंग आणि फर्टिलिटी प्रिझर्व्हेशन',
    'doctor.p4.end': 'सारख्या नवीन तंत्रज्ञानासह इच्छुक पालकांसाठी वैयक्तिकृत काळजी आणि उत्कृष्ट परिणाम दिले जातात.',
    'doctor.cta': 'अपॉइंटमेंट बुक करा',
    'hero.title': 'पालकत्वाचे स्वप्न पाहताय?',
    'hero.subtitle': 'प्रगत आयव्हीएफ केअरसह तुमची वाटचाल इथून सुरू होते',
    'hero.badge': 'विशेष ऑफर',
    'hero.bookAppointment': 'अपॉइंटमेंट बुक करा',
    'hero.selectService': 'सेवा निवडा',
    'hero.service.ivf': 'आयव्हीएफ उपचार',
    'hero.service.consultation': 'सल्लामसलत',
    'hero.service.gynaecologist': 'स्त्रीरोगतज्ज्ञ',
    'hero.input.name': 'तुमचे नाव',
    'hero.input.email': 'ईमेल पत्ता (ऐच्छिक)',
    'hero.input.phone': 'फोन नंबर',
    'hero.requestCallback': 'कॉलबॅकची विनंती करा',
    'hero.status.sending': 'तुमची विनंती पाठवली जात आहे...',
    'hero.status.success': 'विनंती यशस्वीरीत्या पाठवली! आम्ही लवकरच संपर्क करू.',
    'hero.status.failed': 'विनंती पाठवण्यात अयशस्वी. कृपया पुन्हा प्रयत्न करा.',
    'lang.english': 'इंग्रजी',
    'lang.hindi': 'हिंदी',
    'lang.marathi': 'मराठी',
  },
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage,
      t: (key: string) => translations[language][key] ?? translations.en[key] ?? key,
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = (): LanguageContextValue => {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }

  return context;
};
